import Navbar from "../components/Navbar";

const Dashboard = () => {
  return (
    <div>
      Dashboard
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <p>feed content</p>
      <Navbar />
      <p>feed content</p>
    </div>
  );
};

export default Dashboard;
